version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-workshop-lab1"
s3_bucket = "sam-bootstrap-bucket-bdd95af9-0e28-4609-8080-8af0d3d2fbd5"
s3_prefix = "serverless-saas-lab1"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
cached="true"
parallel="true"
