# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Lab1 - Lambda functions and API Gateway
Parameters:
  StageName:
    Type: String
    Default: "prod"
    Description: "Stage Name for the api"
Resources:
  LambdaFunctions:
    Type: AWS::Serverless::Application
    Properties:
      Location: nested_templates/lambdafunctions.yaml

  APIs:
    Type: AWS::Serverless::Application
    DependsOn: LambdaFunctions
    Properties:
      Location: nested_templates/apigateway.yaml
      Parameters:
        StageName: !Ref StageName
        GetProductFunctionArn: !GetAtt LambdaFunctions.Outputs.GetProductFunctionArn
        GetProductsFunctionArn: !GetAtt LambdaFunctions.Outputs.GetProductsFunctionArn
        CreateProductFunctionArn: !GetAtt LambdaFunctions.Outputs.CreateProductFunctionArn
        UpdateProductFunctionArn: !GetAtt LambdaFunctions.Outputs.UpdateProductFunctionArn
        DeleteProductFunctionArn: !GetAtt LambdaFunctions.Outputs.DeleteProductFunctionArn
        GetOrdersFunctionArn: !GetAtt LambdaFunctions.Outputs.GetOrdersFunctionArn
        GetOrderFunctionArn: !GetAtt LambdaFunctions.Outputs.GetOrderFunctionArn
        CreateOrderFunctionArn: !GetAtt LambdaFunctions.Outputs.CreateOrderFunctionArn
        UpdateOrderFunctionArn: !GetAtt LambdaFunctions.Outputs.UpdateOrderFunctionArn
        DeleteOrderFunctionArn: !GetAtt LambdaFunctions.Outputs.DeleteOrderFunctionArn

  APIGatewayLambdaPermissions:
    Type: AWS::Serverless::Application
    DependsOn: LambdaFunctions
    Properties:
      Location: nested_templates/apigateway_lambdapermissions.yaml
      Parameters:
        GetProductFunctionArn: !GetAtt LambdaFunctions.Outputs.GetProductFunctionArn
        GetProductsFunctionArn: !GetAtt LambdaFunctions.Outputs.GetProductsFunctionArn
        CreateProductFunctionArn: !GetAtt LambdaFunctions.Outputs.CreateProductFunctionArn
        UpdateProductFunctionArn: !GetAtt LambdaFunctions.Outputs.UpdateProductFunctionArn
        DeleteProductFunctionArn: !GetAtt LambdaFunctions.Outputs.DeleteProductFunctionArn
        GetOrdersFunctionArn: !GetAtt LambdaFunctions.Outputs.GetOrdersFunctionArn
        GetOrderFunctionArn: !GetAtt LambdaFunctions.Outputs.GetOrderFunctionArn
        CreateOrderFunctionArn: !GetAtt LambdaFunctions.Outputs.CreateOrderFunctionArn
        UpdateOrderFunctionArn: !GetAtt LambdaFunctions.Outputs.UpdateOrderFunctionArn
        DeleteOrderFunctionArn: !GetAtt LambdaFunctions.Outputs.DeleteOrderFunctionArn
        ApplicationApiGatewayApi: !GetAtt APIs.Outputs.ApplicationApiGatewayApi

Outputs:
  APIGatewayURL:
    Description: "API Gateway endpoint URL for API"
    Value: !Join ["", ["https://", !GetAtt APIs.Outputs.ApplicationApiGatewayApi, ".execute-api.", !Ref "AWS::Region", ".amazonaws.com/", !Ref StageName]]
  ApplicationSite:
    Value: !ImportValue Serverless-SaaS-ApplicationSite
  AppBucket:
    Value: !ImportValue Serverless-SaaS-ApplicationSiteBucket
