# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to setup api gateway routes on the pre-existing API from shared stack
Parameters:
  StageName:
    Type: String
  RegisterTenantLambdaExecutionRoleArn:
    Type: String
  TenantManagementLambdaExecutionRoleArn:
    Type: String
  RegisterTenantFunctionArn:
    Type: String
  ActivateTenantFunctionArn:
    Type: String
  GetTenantsFunctionArn:
    Type: String
  CreateTenantFunctionArn:
    Type: String
  GetTenantFunctionArn:
    Type: String
  DeactivateTenantFunctionArn:
    Type: String
  UpdateTenantFunctionArn:
    Type: String
  GetUsersFunctionArn:
    Type: String
  GetUserFunctionArn:
    Type: String
  UpdateUserFunctionArn:
    Type: String
  DisableUserFunctionArn:
    Type: String
  CreateTenantAdminUserFunctionArn:
    Type: String
  CreateUserFunctionArn:
    Type: String
  DisableUsersByTenantFunctionArn:
    Type: String
  EnableUsersByTenantFunctionArn:
    Type: String
  AuthorizerFunctionArn:
    Type: String

Resources:
  AdminApiGatewayAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/api-gateway/access-logs-serverless-saas-admin-api
      RetentionInDays: 30

  Authorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: SharedServicesAuthorizer
      Type: TOKEN
      AuthorizerUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerFunctionArn}/invocations"
      AuthorizerResultTtlInSeconds: 60
      IdentitySource: method.request.header.Authorization
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId

  # ==================== API Resources ====================
  RegistrationResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !ImportValue Serverless-SaaS-AdminApiGatewayRootResourceId
      PathPart: registration

  TenantResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !ImportValue Serverless-SaaS-AdminApiGatewayRootResourceId
      PathPart: tenant

  TenantIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref TenantResource
      PathPart: "{tenantid}"

  TenantActivationResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref TenantResource
      PathPart: activation

  TenantActivationIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref TenantActivationResource
      PathPart: "{tenantid}"

  TenantsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !ImportValue Serverless-SaaS-AdminApiGatewayRootResourceId
      PathPart: tenants

  UserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !ImportValue Serverless-SaaS-AdminApiGatewayRootResourceId
      PathPart: user

  UserNameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref UserResource
      PathPart: "{username}"

  UserTenantAdminResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref UserResource
      PathPart: tenant-admin

  UsersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !ImportValue Serverless-SaaS-AdminApiGatewayRootResourceId
      PathPart: users

  UsersDisableResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref UsersResource
      PathPart: disable

  UsersDisableIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref UsersDisableResource
      PathPart: "{tenantid}"

  UsersEnableResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref UsersResource
      PathPart: enable

  UsersEnableIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ParentId: !Ref UsersEnableResource
      PathPart: "{tenantid}"

  # ==================== Methods ====================
  RegistrationPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref RegistrationResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterTenantFunctionArn}/invocations"

  TenantActivationPut:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref TenantActivationIdResource
      HttpMethod: PUT
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ActivateTenantFunctionArn}/invocations"

  TenantsGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref TenantsResource
      HttpMethod: GET
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTenantsFunctionArn}/invocations"

  TenantPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref TenantResource
      HttpMethod: POST
      AuthorizationType: AWS_IAM
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateTenantFunctionArn}/invocations"

  TenantIdGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref TenantIdResource
      HttpMethod: GET
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTenantFunctionArn}/invocations"

  TenantIdDelete:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref TenantIdResource
      HttpMethod: DELETE
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeactivateTenantFunctionArn}/invocations"

  TenantIdPut:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref TenantIdResource
      HttpMethod: PUT
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateTenantFunctionArn}/invocations"

  UserNameGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref UserNameResource
      HttpMethod: GET
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserFunctionArn}/invocations"

  UserNamePut:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref UserNameResource
      HttpMethod: PUT
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateUserFunctionArn}/invocations"

  UserNameDelete:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref UserNameResource
      HttpMethod: DELETE
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisableUserFunctionArn}/invocations"

  UserTenantAdminPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref UserTenantAdminResource
      HttpMethod: POST
      AuthorizationType: AWS_IAM
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateTenantAdminUserFunctionArn}/invocations"

  UserPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref UserResource
      HttpMethod: POST
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateUserFunctionArn}/invocations"

  UsersGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref UsersResource
      HttpMethod: GET
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUsersFunctionArn}/invocations"

  UsersDisablePut:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref UsersDisableIdResource
      HttpMethod: PUT
      AuthorizationType: AWS_IAM
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisableUsersByTenantFunctionArn}/invocations"
        RequestParameters:
          integration.request.header.X-Amz-Invocation-Type: "'Event'"
        RequestTemplates:
          application/json: "{\"tenantid\": \"$input.params('tenantid')\"}"
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  UsersEnablePut:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      ResourceId: !Ref UsersEnableIdResource
      HttpMethod: PUT
      AuthorizationType: AWS_IAM
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EnableUsersByTenantFunctionArn}/invocations"
        RequestParameters:
          integration.request.header.X-Amz-Invocation-Type: "'Event'"
        RequestTemplates:
          application/json: "{\"tenantid\": \"$input.params('tenantid')\"}"
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # ==================== Deployment ====================
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RegistrationPost
      - TenantActivationPut
      - TenantsGet
      - TenantPost
      - TenantIdGet
      - TenantIdDelete
      - TenantIdPut
      - UserNameGet
      - UserNamePut
      - UserNameDelete
      - UserTenantAdminPost
      - UserPost
      - UsersGet
      - UsersDisablePut
      - UsersEnablePut
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !ImportValue Serverless-SaaS-AdminApiGatewayId
      DeploymentId: !Ref ApiDeployment
      StageName: !Ref StageName
      AccessLogSetting:
        DestinationArn: !GetAtt AdminApiGatewayAccessLogs.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller","user":"$context.identity.user","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength"}'
      MethodSettings:
        - DataTraceEnabled: false
          LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: "/*"
          HttpMethod: "*"
      TracingEnabled: true

Outputs:
  AdminApiGatewayApi:
    Value: !ImportValue Serverless-SaaS-AdminApiGatewayId
