version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-pooled"
resolve_s3 = true
s3_prefix = "serverless-saas-tenant"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"

