build-%:
	cp -r . $(ARTIFACTS_DIR)/
	cp ../Resources/logger.py ../Resources/utils.py ../Resources/auth_manager.py ../Resources/metrics_manager.py $(ARTIFACTS_DIR)/
	pip install -r requirements.txt -t $(ARTIFACTS_DIR)/
