# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to deploy lambda functions as part of bootstrap
Parameters:
  CognitoOperationUsersUserPoolId:
    Type: String
  CognitoOperationUsersUserPoolClientId:
    Type: String
  CognitoUserPoolId:
    Type: String
  CognitoUserPoolClientId:
    Type: String
Globals:
  Function:
    Timeout: 29
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
    Environment:
      Variables:
        LOG_LEVEL: DEBUG
        POWERTOOLS_METRICS_NAMESPACE: "ServerlessSaaS"

Resources:
  SharedServicesAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../Resources/
      Handler: shared_service_authorizer.lambda_handler
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-AuthorizerExecutionRoleArn
      MemorySize: 256
      Tracing: Active
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          OPERATION_USERS_USER_POOL: !Ref CognitoOperationUsersUserPoolId
          OPERATION_USERS_APP_CLIENT: !Ref CognitoOperationUsersUserPoolClientId

  CreateTenantAdminUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: user-management.create_tenant_admin_user
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-CreateUserLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          TENANT_USER_POOL_ID: !Ref CognitoUserPoolId
          TENANT_APP_CLIENT_ID: !Ref CognitoUserPoolClientId
          POWERTOOLS_SERVICE_NAME: "UserManagement.CreateTenantAdmin"

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: user-management.create_user
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-CreateUserLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          TENANT_USER_POOL_ID: !Ref CognitoUserPoolId
          POWERTOOLS_SERVICE_NAME: "UserManagement.CreateUser"

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: user-management.update_user
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantUserPoolLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          TENANT_USER_POOL_ID: !Ref CognitoUserPoolId
          POWERTOOLS_SERVICE_NAME: "UserManagement.UpdateUser"

  DisableUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: user-management.disable_user
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantUserPoolLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          TENANT_USER_POOL_ID: !Ref CognitoUserPoolId
          POWERTOOLS_SERVICE_NAME: "UserManagement.DisableUser"

  DisableUsersByTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: user-management.disable_users_by_tenant
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantUserPoolLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          TENANT_USER_POOL_ID: !Ref CognitoUserPoolId
          POWERTOOLS_SERVICE_NAME: "UserManagement.DisableUsersByTenant"

  EnableUsersByTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: user-management.enable_users_by_tenant
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantUserPoolLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          TENANT_USER_POOL_ID: !Ref CognitoUserPoolId
          POWERTOOLS_SERVICE_NAME: "UserManagement.EnableUsersByTenant"

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: user-management.get_user
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantUserPoolLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          TENANT_USER_POOL_ID: !Ref CognitoUserPoolId
          POWERTOOLS_SERVICE_NAME: "UserManagement.GetUser"

  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: user-management.get_users
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantUserPoolLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          TENANT_USER_POOL_ID: !Ref CognitoUserPoolId
          POWERTOOLS_SERVICE_NAME: "UserManagement.GetUsers"

  CreateTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: tenant-management.create_tenant
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantManagementLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: "TenantManagement.CreateTenant"

  ActivateTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: tenant-management.activate_tenant
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantManagementLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: "TenantManagement.ActivateTenant"
          ENABLE_USERS_BY_TENANT: "/users/enable"
          PROVISION_TENANT: "/provisioning/"

  GetTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: tenant-management.get_tenant
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantManagementLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: "TenantManagement.GetTenant"

  DeactivateTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: tenant-management.deactivate_tenant
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantManagementLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: "TenantManagement.DeactivateTenant"
          DEPROVISION_TENANT: "/provisioning/"
          DISABLE_USERS_BY_TENANT: "/users/disable"

  UpdateTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: tenant-management.update_tenant
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantManagementLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: "TenantManagement.UpdateTenant"

  GetTenantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: tenant-management.get_tenants
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-TenantManagementLambdaExecutionRoleArn
      Tracing: Active
      TenancyConfig:
        TenantIsolationMode: PER_TENANT
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn

  RegisterTenantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../TenantManagementService/
      Handler: tenant-registration.register_tenant
      Runtime: python3.14
      Role: !ImportValue Serverless-SaaS-RegisterTenantLambdaExecutionRoleArn
      Tracing: Active
      Layers:
        - !ImportValue Serverless-SaaS-LayerArn
      Environment:
        Variables:
          CREATE_TENANT_ADMIN_USER_RESOURCE_PATH: "/user/tenant-admin"
          CREATE_TENANT_RESOURCE_PATH: "/tenant"
          PROVISION_TENANT_RESOURCE_PATH: "/provisioning"
          POWERTOOLS_SERVICE_NAME: "TenantRegistration.RegisterTenant"

Outputs:
  RegisterTenantLambdaExecutionRoleArn:
    Value: !ImportValue Serverless-SaaS-RegisterTenantLambdaExecutionRoleArn
  TenantManagementLambdaExecutionRoleArn:
    Value: !ImportValue Serverless-SaaS-TenantManagementLambdaExecutionRoleArn
  RegisterTenantFunctionArn:
    Value: !GetAtt RegisterTenantFunction.Arn
  ActivateTenantFunctionArn:
    Value: !GetAtt ActivateTenantFunction.Arn
  GetTenantsFunctionArn:
    Value: !GetAtt GetTenantsFunction.Arn
  CreateTenantFunctionArn:
    Value: !GetAtt CreateTenantFunction.Arn
  GetTenantFunctionArn:
    Value: !GetAtt GetTenantFunction.Arn
  DeactivateTenantFunctionArn:
    Value: !GetAtt DeactivateTenantFunction.Arn
  UpdateTenantFunctionArn:
    Value: !GetAtt UpdateTenantFunction.Arn
  GetUsersFunctionArn:
    Value: !GetAtt GetUsersFunction.Arn
  GetUserFunctionArn:
    Value: !GetAtt GetUserFunction.Arn
  UpdateUserFunctionArn:
    Value: !GetAtt UpdateUserFunction.Arn
  DisableUserFunctionArn:
    Value: !GetAtt DisableUserFunction.Arn
  CreateTenantAdminUserFunctionArn:
    Value: !GetAtt CreateTenantAdminUserFunction.Arn
  CreateUserFunctionArn:
    Value: !GetAtt CreateUserFunction.Arn
  DisableUsersByTenantFunctionArn:
    Value: !GetAtt DisableUsersByTenantFunction.Arn
  EnableUsersByTenantFunctionArn:
    Value: !GetAtt EnableUsersByTenantFunction.Arn
  SharedServicesAuthorizerFunctionArn:
    Value: !GetAtt SharedServicesAuthorizerFunction.Arn
