version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-cost-per-tenant-lab7"
resolve_s3 = true
s3_prefix = "serverless-saas-lab7"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"