version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-pooled-lab7"
resolve_s3 = true
capabilities = "CAPABILITY_NAMED_IAM"
region = "us-west-2"
confirm_changeset = false
fail_on_empty_changeset = false
